apiVersion: v1
kind: Service
metadata:
  name: docker-build-service
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - nodePort: 31150   #Specify node port for cluster
      port: 8080        #Match with Flask application
      targetPort: 80    #Listen for Port 80